name: Build and test
on: push
jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: yarn
      - run: pushd frontend
      - name: Install dependencies
        run: yarn install
      - run: popd
  test-files:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: pushd frontend
      - name: Run lint
        run: yarn lint
      - name: Run tests
        run: yarn test
      - run: popd
    
  build-files:
    needs: [install-dependencies]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: pushd frontend
      - name: Run build
        run: yarn build
      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ${{ github.workspace }}/frontend/dist/*
          key: ${{ github.sha }}
      - run: popd
